// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFpmcwW37NiwO1xTCZyBUMd6PVvemXjq0',
    appId: '1:480501553805:web:2078ed976a6c017e3d60c4',
    messagingSenderId: '480501553805',
    projectId: 'eventhorizon-8a65b',
    authDomain: 'eventhorizon-8a65b.firebaseapp.com',
    storageBucket: 'eventhorizon-8a65b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxiuzzKXMUHTpwo8xvLFr6OPTh9osWcoA',
    appId: '1:480501553805:android:9ea437e4eced7a803d60c4',
    messagingSenderId: '480501553805',
    projectId: 'eventhorizon-8a65b',
    storageBucket: 'eventhorizon-8a65b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjcATQUsAspc9_-_eZ5z_FzvQLs3wFsXQ',
    appId: '1:480501553805:ios:9cb51b7c86768f983d60c4',
    messagingSenderId: '480501553805',
    projectId: 'eventhorizon-8a65b',
    storageBucket: 'eventhorizon-8a65b.firebasestorage.app',
    iosClientId: '480501553805-ocrjmapfljdefuu1va28a4vtd7p6f76h.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventLister',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjcATQUsAspc9_-_eZ5z_FzvQLs3wFsXQ',
    appId: '1:480501553805:ios:9cb51b7c86768f983d60c4',
    messagingSenderId: '480501553805',
    projectId: 'eventhorizon-8a65b',
    storageBucket: 'eventhorizon-8a65b.firebasestorage.app',
    iosClientId: '480501553805-ocrjmapfljdefuu1va28a4vtd7p6f76h.apps.googleusercontent.com',
    iosBundleId: 'com.example.eventLister',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFpmcwW37NiwO1xTCZyBUMd6PVvemXjq0',
    appId: '1:480501553805:web:4c42c13dbc800eb53d60c4',
    messagingSenderId: '480501553805',
    projectId: 'eventhorizon-8a65b',
    authDomain: 'eventhorizon-8a65b.firebaseapp.com',
    storageBucket: 'eventhorizon-8a65b.firebasestorage.app',
  );
}
